/**
 * JS Loader - Generated by JS Encryptor
 * Loader ini mendekripsi dan menjalankan file .enc
 * DO NOT EDIT MANUALLY
 */
(function() {
  'use strict';

  var ENC_FILE = 'bundle.enc';
  var SECRET_KEY = 'Zelix1234567###';

  function loadCryptoJS(callback) {
    if (typeof CryptoJS !== 'undefined') {
      callback();
      return;
    }
    var s = document.createElement('script');
    s.src = 'https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.2.0/crypto-js.min.js';
    s.onload = callback;
    s.onerror = function() {
      console.error('[Loader] Gagal memuat CryptoJS');
    };
    document.head.appendChild(s);
  }

  function fetchAndRun() {
    var basePath = (function() {
      var scripts = document.querySelectorAll('script[src]');
      for (var i = 0; i < scripts.length; i++) {
        var src = scripts[i].getAttribute('src');
        if (src && src.indexOf('script') !== -1) {
          return src.replace(/[^\/]*$/, '');
        }
      }
      return '';
    })();

    var url = basePath + ENC_FILE + '?v=' + Date.now();

    fetch(url)
      .then(function(res) {
        if (!res.ok) throw new Error('HTTP ' + res.status);
        return res.text();
      })
      .then(function(encData) {
        try {
          var bytes = CryptoJS.AES.decrypt(encData.trim(), SECRET_KEY);
          var decrypted = bytes.toString(CryptoJS.enc.Utf8);
          if (!decrypted) throw new Error('Dekripsi gagal - key salah?');
          var fn = new Function(decrypted);
          fn();
        } catch(e) {
          console.error('[Loader] Dekripsi error:', e.message);
        }
      })
      .catch(function(e) {
        console.error('[Loader] Fetch error:', e.message);
      });
  }

  loadCryptoJS(fetchAndRun);
})();
